#Kill all default topologies
storm kill AsyncAdapter &
storm kill CurlAdapter &
storm kill HelloWorldAdapter &
storm kill HelloWorldNodeAdapter &
storm kill HelloWorldPython3Adapter &
storm kill HelloWorldPythonAdapter &
storm kill PlusBangAdapter &
storm kill CoordinatorTopology &
